---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  galaxy: requirements.yml
additional_build_steps:
  prepend_galaxy:
    - COPY ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg
...
